### ISSUE TITLE
Add all MDX plugins missing

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/raulmelo.dev#1058]
To keep the same functionality and behaviour, it should be used theses plugins in `next-mdx-remote`: https://github.com/raulfdm/raulmelo.dev/blob/main/projects/web/gatsby-config.js#L78

https://github.com/hashicorp/next-mdx-remote#apis

## TODOS

- [ ] gatsby-remark-responsive-iframe
- [ ] gatsby-remark-images -> not needed
- [x] remark-unwrap-images (If needed)
- [x] gatsby-remark-code-titles
- [x] gatsby-remark-autolink-headers
- [x] gatsby-remark-prismjs
 - this is partially true. See comment below

### Code Highlight and lines

Couldn't manage how to do. It seems the plugins and ecosystem isn't good enough.

**Comment by raulfdm** [comment]
Highlight is fixed here: https://github.com/raulfdm/raulmelo.dev-next/pull/40

**Comment by raulfdm** [comment]
I didn't find any `responsive-iframe` plugin but I noticed that is not needed because I can easily add a custom `<Iframe>` component to make it responsive via MDX components.

**Comment by raulfdm** [comment]
`remark-images` is also not needed because I'm going to use NextJS image components

**Comment by raulfdm** [comment]
The only piece I couldn't figure out was code line number but it's ok. I've fixed the code highlight which already helps in this problem
